name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:                    # <-- variables de entorno disponibles en todos los steps
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/cmdline-tools/bin:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Install JDK and Android Commandline Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk unzip wget
          # descargar commandline tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools

          # instalar paquetes requeridos antes de licencias
          yes | $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;36.1.0"

          # aceptar licencias de todo
          yes | $ANDROID_HOME/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Compile Kivy App
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiCalculadora
          path: bin/*.apk
