name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Android APK
        uses: daniel-santos/kivy-buildozer-action@v1.1
        with:
          buildozer_spec_path: buildozer.spec
