name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git openjdk-17-jdk wget unzip

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Accept licenses and install Android SDK components
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        mkdir -p ~/.android && echo "count=0" > ~/.android/repositories.cfg
        yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
        yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "build-tools;33.0.2" "platforms;android-33"

    - name: Build APK with Buildozer
      env:
        ANDROID_HOME: ${{ runner.home }}/android-sdk
        PATH: /usr/bin:/bin:${{ runner.home }}/android-sdk/cmdline-tools/latest/bin:${{ runner.home }}/android-sdk/platform-tools:${{ env.PATH }}
      run: |
        # Forzar a Buildozer a usar build-tools 33.0.2
        sed -i 's/^# *android\.sdk_path =.*/android.sdk_path = \/home\/runner\/android-sdk/' buildozer.spec || true
        sed -i 's/^# *android\.sdk\.api =.*/android.sdk.api = 33/' buildozer.spec || true
        sed -i 's/^# *android\.ndk_path =.*/android.ndk_path = \/home\/runner\/.buildozer\/android\/platform\/android-ndk/' buildozer.spec || true
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app.apk
        path: bin/*.apk
